# .NET Core Function App to Windows on Azure
# Build a .NET Core function app and deploy it to Azure as a Windows function App.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - main
    - master
  
variables:
    # Azure Resource Manager connection
    azureSubscription: 'internal_azure_subscription'

    # resource group to target for deployment
    resourceGroupName: 'pepper-poc-rg'

    # location
    location: 'australiaeast'

    # Agent VM image name
    vmImageName: 'windows-latest'

    # function App Name
    functionAppName: 'func-tdtwi4'

    configuration: 'Release'

stages:
  - stage: Build
    displayName: Build
  
    jobs:
    - job: BuildFunctionAppJob
      displayName: 'Build PGPEncrypt Job'
      pool:
        vmImage: $(vmImageName)
  
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'Build function App'
        inputs:
          command: 'build'
          projects: |
            src/functionApp/*.csproj
          arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration $(configuration)
  
      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/functionApp.$(Build.BuildId).zip
          replaceExistingArchive: true
  
      - publish: $(Build.ArtifactStagingDirectory)/functionApp.$(Build.BuildId).zip
        artifact: functionApp_drop

    - job: BuildConsoleAppJob
      displayName: 'Build Console App Job'
      pool:
        vmImage: $(vmImageName)

      steps:
      - task: DotNetCoreCLI@2
        displayName: 'Build Console App Task Step'
        inputs:
          command: 'build'
          projects: |
            src/consoleApp/*.csproj
          arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration $(configuration)
      
      - publish: $(Build.ArtifactStagingDirectory)/consoleApp.$(Build.BuildId).zip
        artifact: PGPEncryptConsoleApp_drop

      - task: ArchiveFiles@2
        displayName: 'Archive files Task Step'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/consoleApp.$(Build.BuildId).zip
          replaceExistingArchive: true

      - task: CopyFiles@2
        displayName: 'Copy Files Task Step'
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/deploy'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/deploy'

      - publish: $(Build.ArtifactStagingDirectory)/deploy
        artifact: arm_template_drop

  - stage: DeployFunctionsToAzure
    displayName: 'Deploy Azure Functions'
    dependsOn: Build
    condition: succeeded()
  
    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: 'development'
      pool:
        vmImage: $(vmImageName)
      strategy:
        runOnce:
          deploy:
            steps:
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'validate infrastructure template'
              inputs:
                action: Create Or Update Resource Group
                azureResourceManagerConnection: '$(azureSubscription)'
                csmFile: $(Pipeline.Workspace)/arm_template_drop/azuredeploy.json
                csmParametersFile: $(Pipeline.Workspace)/arm_template_drop/azuredeploy.parameters.json
                resourceGroupName: $(resourceGroupName)
                location: $(location)
                deploymentMode: Validation
                deploymentScope: Resource Group
                overrideParameters: -location $(location)

            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'deploy infrastructure template'
              inputs:
                action: Create Or Update Resource Group
                azureResourceManagerConnection: '$(azureSubscription)'
                csmFile: $(Pipeline.Workspace)/arm_template_drop/azuredeploy.json
                csmParametersFile: $(Pipeline.Workspace)/arm_template_drop/azuredeploy.parameters.json
                resourceGroupName: $(resourceGroupName)
                location: $(location)
                deploymentMode: Incremental
                deploymentScope: Resource Group
                deploymentName: 'deploy-infrastructure'
                overrideParameters: -location $(location)
                deploymentOutputs: infraDeploymentOutputs

            - task: PowerShell@2
              displayName: 'Get ARM Deployment Outputs'
              inputs:
                targetType: 'inline'
                script: |
                  $outputs = '$(infraDeploymentOutputs)' | ConvertFrom-Json
                  foreach ($output in $outputs.PSObject.Properties) {
                    Write-Host "$($output.Name) - $($output.Value.value)"
                    Write-Host "##vso[task.setvariable variable=$($output.Name);]$($output.Value.value)" 
                  }
  
            - task: AzureFunctionApp@1
              displayName: 'Function App deployment'
              inputs:
                azureSubscription: '$(azureSubscription)'
                resourceGroupName: $(resourceGroupName)
                appType: functionApp
                appName: $(functionAppName)
                deploymentMethod: zipDeploy
                package: '$(Pipeline.Workspace)/functionApp_drop/functionApp.$(Build.BuildId).zip'

            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'validate logic app template'
              inputs:
                action: Create Or Update Resource Group
                azureResourceManagerConnection: '$(azureSubscription)'
                csmFile: $(Pipeline.Workspace)/arm_template_drop/azuredeploy-logic-app.json
                csmParametersFile: $(Pipeline.Workspace)/arm_template_drop/azuredeploy-logic-app.parameters.json
                resourceGroupName: $(resourceGroupName)
                location: $(location)
                deploymentMode: Validation
                deploymentScope: Resource Group
                overrideParameters: -location $(location)

            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'deploy logic app template'
              inputs:
                action: Create Or Update Resource Group
                azureResourceManagerConnection: '$(azureSubscription)'
                csmFile: $(Pipeline.Workspace)/arm_template_drop/azuredeploy-logic-app.json
                csmParametersFile: $(Pipeline.Workspace)/arm_template_drop/azuredeploy-logic-app.parameters.json
                resourceGroupName: $(resourceGroupName)
                location: $(location)
                deploymentMode: Incremental
                deploymentScope: Resource Group
                deploymentName: 'deploy-infrastructure'
                overrideParameters: -location $(location)
                deploymentOutputs: logicAppDeploymentOutputs
